# Generated by Django 4.2.15 on 2024-08-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="acttive",
            new_name="active",
        ),
    ]
