name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        # poetry-version: [1.1.4] # Removido para utilizar sempre a versão mais recente

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Atualizado para v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Atualizado para v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the latest Poetry version
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry  # Instala a versão mais recente do Poetry

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Test
      run: |
        poetry run python manage.py test
